library(shiny)  

checkBoxChoices <- list("Number of cylinders" = "cyl", 
                        "Displacement (cu.in.)" = "disp",
                        "Gross horsepower" = "hp",
                        "Rear axle ratio" = "drat",
                        "Weight (lb/1000)" = "wt",
                        "1/4 mile time" = "qsec",
                        "V/S (inline engine" = "vs",
                        "Transmission Type (Automatic/Manual)" = "am",
                        "Number of forward gears" = "gear",
                        "Number of carburetors" = "carb")

initialSelections <- list("Gross horsepower" = "hp",
                          "Weight (lb/1000)" = "wt",
                          "Transmission Type (Automatic/Manual)" = "am")

shinyUI(pageWithSidebar( 
    
    headerPanel("Multiple Linear Regression Model Example"), 
    
    sidebarPanel(
        checkboxGroupInput(predictorVariables <- "predictorVariables",
                           label <- "mtcars data set MPG predictor variables",
                           choices <- checkBoxChoices,
                           selections <- initialSelections),
        submitButton(text = "Apply Changes", icon = NULL)
    ),
    
    mainPanel( 
        tabsetPanel(
            tabPanel("Segmented data",
                     div(class="segmentedDataTab", checked=NA,
                         p(paste("This tab displays the vehicle, its fuel ",
                                 "efficiency, and the predictor variables",
                                 "selected by a user. The following ",
                                 "R commands display additional information",
                                 "about this data set:")),
                           tags$ol(
                               tags$li("library(datasets)"), 
                               tags$li("data(mtcars)"), 
                               tags$li("?mtcars")
                           )),
                     dataTableOutput('segmentedData')),
            tabPanel("EDA",
                     div(class="edaTab", checked=NA,
                         h3("Exploratory Data Analysis"),
                         p(paste("This tab displays a pairs plot generated ",
                                 "using the ggpairs() function from the ",
                                 "GGally package. The purpose of this plot is",
                                 "to evaluate the relationship between",
                                 "predictor variable pairs. Depending on the ",
                                 "number of predictor variables selected, it ",
                                 "may require several seconds for the Shiny",
                                 "application server to render this plot."))),
                     plotOutput("edaPlot")),
            tabPanel("lm() Output Summary",
                     div(class="edaTab", checked=NA,
                         h3("Multiple Linear Regression Model Fit"),
                         p(paste("This table displays a summary of the",
                                 "multiple linear regression model fit",
                                 "generated by lm(). Variables whose ",
                                 "Pr(>|t|) value is less than 0.05 are",
                                 "significant predictors of a vehicle's",
                                 "fuel efficiency at the 5% level."))),
                     verbatimTextOutput("lmSummary")),
            tabPanel("lm() Output Diagnostics",
                     h2("Multiple Linear Regression Model Diagnostics"),
                     plotOutput("lmModelDiagnostics"))
        )
    )
))